package com.sinc.enhanced.ui.theme

// GENERATED by build-scripts/gen-tokens.mjs from design-tokens.json - do not edit.
import androidx.compose.ui.graphics.Color

// Semantic tokens (dark - the product surface)
val Ink = Color(0xFF0B0F19)
val Surface = Color(0xFF131826)
val SurfaceHigh = Color(0xFF1B2233)
val Emerald = Color(0xFF10B981)
val EmeraldStrong = Color(0xFF059669)
val Amber = Color(0xFFF0B429)
val Coral = Color(0xFFE8615F)
val TextHigh = Color(0xFFF5F7FA)
val TextMid = Color(0xFF9AA3B5)
val TextLow = Color(0xFF5C6478)
val Hairline = Color(0xFF232B3D)

// Deprecated aliases - prefer the tokens above. New code uses Ink/Surface/Emerald/Amber/...
val Primary = Emerald
val PrimaryDark = EmeraldStrong
val Secondary = Amber
val Background = Ink
val OnSurface = TextHigh
val OnSurfaceVariant = TextMid
val Error = Coral
val ErrorContainer = Color(0xFF7F1D1D)
val Outline = Hairline
val SurfaceLight = SurfaceHigh
val Scrim = Color(0xE60B0F19)
