#!/usr/bin/env node
/**
 * Generates platform code/style from design-tokens.json (single source of truth).
 *
 * Outputs:
 *   - frontend/src/index.css        -> Tailwind v4 @theme block (between markers)
 *   - app/.../ui/theme/Color.kt     -> full overwrite
 *   - app/.../ui/theme/Type.kt      -> full overwrite
 *
 * Run from repo root: node build-scripts/gen-tokens.mjs
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = dirname(dirname(fileURLToPath(import.meta.url)))
const tokens = JSON.parse(readFileSync(resolve(ROOT, 'design-tokens.json'), 'utf8'))

const DARK = tokens.colors.dark
const LIGHT = tokens.colors.light
const TYPE = {
  sm: tokens.typeScale['display-sm'],
  md: tokens.typeScale.display,
  lg: tokens.typeScale['display-lg'],
}

function alpha(hex, a) {
  const v = parseInt(hex.replace('#', ''), 16)
  return `rgba(${(v >> 16) & 255},${(v >> 8) & 255},${v & 255},${a})`
}

// ---------------------------------------------------------------------------
// Web: Tailwind v4 @theme block
// ---------------------------------------------------------------------------
function webThemeBlock() {
  const lines = [
    '/* design-tokens:start */',
    '/* GENERATED by build-scripts/gen-tokens.mjs from design-tokens.json - do not edit. */',
    '@theme {',
    '  /* Palette: dark (the product surface) */',
    `  --color-dark-bg: ${DARK.ink};`,
    `  --color-dark-surface: ${DARK.surface};`,
    `  --color-dark-surface-2: ${DARK['surface-high']};`,
    `  --color-dark-border: ${DARK.hairline};`,
    `  --color-dark-text: ${DARK['text-high']};`,
    `  --color-dark-muted: ${DARK['text-mid']};`,
    `  --color-dark-muted-low: ${DARK['text-low']};`,
    '',
    '  /* Palette: light */',
    `  --color-light-bg: ${LIGHT.ink};`,
    `  --color-light-surface: ${LIGHT.surface};`,
    `  --color-light-surface-2: ${LIGHT['surface-high']};`,
    `  --color-light-border: ${LIGHT.hairline};`,
    `  --color-light-text: ${LIGHT['text-high']};`,
    `  --color-light-muted: ${LIGHT['text-mid']};`,
    `  --color-light-muted-low: ${LIGHT['text-low']};`,
    '',
    '  /* Semantic tokens (prefer these in new screens) */',
    `  --color-ink: ${DARK.ink};`,
    `  --color-surface: ${DARK.surface};`,
    `  --color-surface-high: ${DARK['surface-high']};`,
    `  --color-emerald: ${DARK.emerald};`,
    `  --color-emerald-strong: ${DARK['emerald-strong']};`,
    `  --color-amber: ${DARK.amber};`,
    `  --color-coral: ${DARK.coral};`,
    `  --color-text-high: ${DARK['text-high']};`,
    `  --color-text-mid: ${DARK['text-mid']};`,
    `  --color-text-low: ${DARK['text-low']};`,
    `  --color-hairline: ${DARK.hairline};`,
    '',
    '  /* Legacy accent aliases (deprecated, compatibility) */',
    `  --color-accent: ${DARK.emerald};`,
    `  --color-accent-hover: ${DARK['emerald-strong']};`,
    `  --color-accent-subtle: ${alpha(DARK.emerald, 0.1)};`,
    `  --color-accent-surface: ${alpha(DARK.emerald, 0.08)};`,
    `  --color-amber-subtle: ${alpha(DARK.amber, 0.12)};`,
    `  --color-coral-subtle: ${alpha(DARK.coral, 0.12)};`,
    '',
    '  /* Fonts: IBM Plex designed pair (Latin + Arabic) and Mono for data */',
    `  --font-sans: '${tokens.fontFamilies.sans.join(`', '`)}', system-ui, -apple-system, sans-serif;`,
    `  --font-mono: '${tokens.fontFamilies.mono}', ui-monospace, 'SF Mono', monospace;`,
    '',
    '  /* Display scale (responsive: sm / md / lg) */',
    `  --text-display-sm: ${TYPE.sm.fontSize / 16}rem;`,
    `  --text-display-sm--line-height: ${TYPE.sm.lineHeight / 16}rem;`,
    `  --text-display: ${TYPE.md.fontSize / 16}rem;`,
    `  --text-display--line-height: ${TYPE.md.lineHeight / 16}rem;`,
    `  --text-display-lg: ${TYPE.lg.fontSize / 16}rem;`,
    `  --text-display-lg--line-height: ${TYPE.lg.lineHeight / 16}rem;`,
    '}',
    '/* design-tokens:end */',
    '',
  ]
  return lines.join('\n')
}

// ---------------------------------------------------------------------------
// Android: Color.kt
// ---------------------------------------------------------------------------
function androidColorKt() {
  return `package com.sinc.enhanced.ui.theme

// GENERATED by build-scripts/gen-tokens.mjs from design-tokens.json - do not edit.
import androidx.compose.ui.graphics.Color

// Semantic tokens (dark - the product surface)
val Ink = Color(0xFF${DARK.ink.slice(1)})
val Surface = Color(0xFF${DARK.surface.slice(1)})
val SurfaceHigh = Color(0xFF${DARK['surface-high'].slice(1)})
val Emerald = Color(0xFF${DARK.emerald.slice(1)})
val EmeraldStrong = Color(0xFF${DARK['emerald-strong'].slice(1)})
val Amber = Color(0xFF${DARK.amber.slice(1)})
val Coral = Color(0xFF${DARK.coral.slice(1)})
val TextHigh = Color(0xFF${DARK['text-high'].slice(1)})
val TextMid = Color(0xFF${DARK['text-mid'].slice(1)})
val TextLow = Color(0xFF${DARK['text-low'].slice(1)})
val Hairline = Color(0xFF${DARK.hairline.slice(1)})

// Deprecated aliases - prefer the tokens above. New code uses Ink/Surface/Emerald/Amber/...
val Primary = Emerald
val PrimaryDark = EmeraldStrong
val Secondary = Amber
val Background = Ink
val OnSurface = TextHigh
val OnSurfaceVariant = TextMid
val Error = Coral
val ErrorContainer = Color(0xFF7F1D1D)
val Outline = Hairline
val SurfaceLight = SurfaceHigh
val Scrim = Color(0xE60B0F19)
`
}

// ---------------------------------------------------------------------------
// Android: Type.kt
// ---------------------------------------------------------------------------
function androidTypeKt() {
  const { mono } = tokens.typeScale
  return `package com.sinc.enhanced.ui.theme

// GENERATED (build-scripts/gen-tokens.mjs + design-tokens.json) - do not edit.
import androidx.compose.material3.Typography
import androidx.compose.ui.text.TextStyle
import androidx.compose.ui.text.font.Font
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.sp
import com.sinc.enhanced.R

// IBM Plex designed pair: Plex Sans (Latin) + Plex Sans Arabic (fallback in-family).
val PlexSans = FontFamily(
    Font(R.font.plex_sans_regular, FontWeight.Normal),
    Font(R.font.plex_sans_semibold, FontWeight.SemiBold),
    Font(R.font.plex_sans_bold, FontWeight.Bold),
    Font(R.font.plex_sans_arabic_regular, FontWeight.Normal),
    Font(R.font.plex_sans_arabic_semibold, FontWeight.SemiBold)
)

val PlexMono = FontFamily(Font(R.font.plex_mono_regular, FontWeight.Normal))

// Tabular data (durations, bitrates, sizes, timestamps).
val DataMono = TextStyle(
    fontFamily = PlexMono,
    fontWeight = FontWeight.Normal,
    fontSize = ${mono.fontSize}.sp,
    lineHeight = ${mono.lineHeight}.sp
)

val Typography = Typography(
    displayLarge = TextStyle(
        fontFamily = PlexSans,
        fontWeight = FontWeight.SemiBold,
        fontSize = ${TYPE.md.fontSize}.sp,
        lineHeight = ${TYPE.md.lineHeight}.sp,
        letterSpacing = 0.sp
    ),
    displayMedium = TextStyle(
        fontFamily = PlexSans,
        fontWeight = FontWeight.SemiBold,
        fontSize = ${TYPE.md.fontSize}.sp,
        lineHeight = ${TYPE.md.lineHeight}.sp,
        letterSpacing = 0.sp
    ),
    displaySmall = TextStyle(
        fontFamily = PlexSans,
        fontWeight = FontWeight.SemiBold,
        fontSize = ${TYPE.sm.fontSize}.sp,
        lineHeight = ${TYPE.sm.lineHeight}.sp,
        letterSpacing = 0.sp
    ),
    headlineLarge = TextStyle(
        fontFamily = PlexSans,
        fontWeight = FontWeight.SemiBold,
        fontSize = ${TYPE.sm.fontSize}.sp,
        lineHeight = ${TYPE.sm.lineHeight}.sp,
        letterSpacing = 0.sp
    ),
    headlineMedium = TextStyle(
        fontFamily = PlexSans,
        fontWeight = FontWeight.SemiBold,
        fontSize = 22.sp,
        lineHeight = 28.sp,
        letterSpacing = 0.sp
    ),
    titleLarge = TextStyle(
        fontFamily = PlexSans,
        fontWeight = FontWeight.SemiBold,
        fontSize = 18.sp,
        lineHeight = 24.sp,
        letterSpacing = 0.sp
    ),
    titleMedium = TextStyle(
        fontFamily = PlexSans,
        fontWeight = FontWeight.Medium,
        fontSize = 16.sp,
        lineHeight = 22.sp,
        letterSpacing = 0.15.sp
    ),
    bodyLarge = TextStyle(
        fontFamily = PlexSans,
        fontWeight = FontWeight.Normal,
        fontSize = ${tokens.typeScale.body.fontSize}.sp,
        lineHeight = ${tokens.typeScale.body.lineHeight}.sp,
        letterSpacing = 0.5.sp
    ),
    bodyMedium = TextStyle(
        fontFamily = PlexSans,
        fontWeight = FontWeight.Normal,
        fontSize = 14.sp,
        lineHeight = 20.sp,
        letterSpacing = 0.25.sp
    ),
    bodySmall = TextStyle(
        fontFamily = PlexSans,
        fontWeight = FontWeight.Normal,
        fontSize = ${tokens.typeScale.caption.fontSize}.sp,
        lineHeight = ${tokens.typeScale.caption.lineHeight}.sp,
        letterSpacing = 0.4.sp
    ),
    labelLarge = TextStyle(
        fontFamily = PlexSans,
        fontWeight = FontWeight.Medium,
        fontSize = 14.sp,
        lineHeight = 20.sp,
        letterSpacing = 0.1.sp
    ),
    labelSmall = TextStyle(
        fontFamily = PlexSans,
        fontWeight = FontWeight.Medium,
        fontSize = 11.sp,
        lineHeight = 16.sp,
        letterSpacing = 0.5.sp
    )
)
`
}

// ---------------------------------------------------------------------------
// main
// ---------------------------------------------------------------------------
const webCssPath = resolve(ROOT, 'frontend/src/index.css')
const css = readFileSync(webCssPath, 'utf8')
const block = webThemeBlock()

const START_MARK = /\/\* design-tokens:start \*\/\n/
const END_MARK = /\/\* design-tokens:end \*\/\n/

let nextCss
if (START_MARK.test(css) && END_MARK.test(css)) {
  // Regenerate in place between markers.
  nextCss = css.replace(
    /\/\* design-tokens:start \*\/[\s\S]*?\/\* design-tokens:end \*\/\n/,
    block,
  )
} else {
  const bareTheme = css.match(/@theme\s*\{[\s\S]*?\}/)
  if (bareTheme) {
    // Replace the pre-existing hand-written @theme block with the generated one.
    nextCss = css.replace(bareTheme[0], block)
  } else {
    nextCss = css.replace(/(@import "tailwindcss";\n)/, '$1' + block)
  }
}
writeFileSync(webCssPath, nextCss)
console.log('✓ web   frontend/src/index.css')

writeFileSync(
  resolve(ROOT, 'app/src/main/kotlin/com/sinc/enhanced/ui/theme/Color.kt'),
  androidColorKt(),
)
console.log('✓ android Color.kt')

writeFileSync(
  resolve(ROOT, 'app/src/main/kotlin/com/sinc/enhanced/ui/theme/Type.kt'),
  androidTypeKt(),
)
console.log('✓ android Type.kt')